"""
Orchestrator Agent
==================

Main coordinator for multi-agent system:
- Routes queries to appropriate agents
- Combines responses from multiple agents
- Manages agent priorities and fallbacks
"""

from typing import Dict, List, Any, Optional
from loguru import logger

from .base_agent import AgentResponse
from .player_agent import PlayerAgent
from .tactical_agent import TacticalAgent


class OrchestratorAgent:
    """
    Orchestrator for routing and coordinating agent responses
    """
    
    def __init__(self, vector_db, llm=None):
        """
        Initialize orchestrator with all specialized agents
        
        Args:
            vector_db: VectorDatabase instance
            llm: Optional LLM instance for answer synthesis
        """
        self.vector_db = vector_db
        self.llm = llm
        
        # Initialize specialized agents
        self.player_agent = PlayerAgent(vector_db, llm)
        self.tactical_agent = TacticalAgent(vector_db, llm)
        
        self.agents = [
            self.player_agent,
            self.tactical_agent
        ]
        
        logger.info("OrchestratorAgent initialized with 2 specialized agents")
    
    def route_query(self, query: str) -> List[str]:
        """
        Determine which agents should handle the query
        
        Args:
            query: User query string
            
        Returns:
            List of agent names that can handle the query
        """
        capable_agents = []
        
        for agent in self.agents:
            if agent.can_handle(query):
                capable_agents.append(agent.agent_name)
                logger.info(f"✓ {agent.agent_name} can handle query")
            else:
                logger.debug(f"✗ {agent.agent_name} cannot handle query")
        
        if not capable_agents:
            logger.warning("No agents can handle query - using fallback")
            capable_agents = [self.player_agent.agent_name]  # Default fallback
        
        return capable_agents
    
    def process_query(self, query: str, multi_agent: bool = False) -> AgentResponse:
        """
        Process query through appropriate agent(s)
        
        Args:
            query: User query string
            multi_agent: If True, combine responses from all capable agents
            
        Returns:
            AgentResponse from primary agent or combined response
        """
        logger.info(f"Orchestrator processing: {query}")
        
        # Route to agents
        capable_agents = self.route_query(query)
        
        if multi_agent and len(capable_agents) > 1:
            return self._combine_responses(query, capable_agents)
        else:
            # Use primary agent only
            primary_agent_name = capable_agents[0]
            agent = next(a for a in self.agents if a.agent_name == primary_agent_name)
            
            response = agent.process(query)
            logger.success(f"Response generated by {primary_agent_name}")
            
            return response
    
    def _combine_responses(self, query: str, agent_names: List[str]) -> AgentResponse:
        """
        Combine responses from multiple agents
        
        Args:
            query: User query string
            agent_names: List of agent names to query
            
        Returns:
            Combined AgentResponse
        """
        logger.info(f"Combining responses from {len(agent_names)} agents")
        
        responses = []
        all_sources = []
        
        for agent_name in agent_names:
            agent = next(a for a in self.agents if a.agent_name == agent_name)
            response = agent.process(query)
            responses.append(response)
            all_sources.extend(response.sources)
        
        # Combine answers
        combined_answer = self._merge_answers(responses)
        
        # Average confidence
        avg_confidence = sum(r.confidence for r in responses) / len(responses)
        
        return AgentResponse(
            agent_name="OrchestratorAgent",
            query=query,
            answer=combined_answer,
            sources=all_sources,
            metadata={'agents_used': agent_names},
            confidence=avg_confidence
        )
    
    def _merge_answers(self, responses: List[AgentResponse]) -> str:
        """
        Merge multiple agent answers into cohesive response
        
        Args:
            responses: List of AgentResponses
            
        Returns:
            Merged answer string
        """
        parts = []
        
        for response in responses:
            parts.append(f"\n{'='*80}")
            parts.append(f"\n{response.agent_name} Response:")
            parts.append(f"\n{'='*80}")
            parts.append(f"\n{response.answer}\n")
        
        return "".join(parts)
    
    def get_agent_status(self) -> Dict[str, Any]:
        """
        Get status of all agents
        
        Returns:
            Dictionary with agent information
        """
        return {
            'total_agents': len(self.agents),
            'agents': [
                {
                    'name': agent.agent_name,
                    'type': 'player' if isinstance(agent, PlayerAgent) else 'tactical',
                    'keyword_count': len(agent.PLAYER_KEYWORDS if isinstance(agent, PlayerAgent) else agent.TACTICAL_KEYWORDS)
                }
                for agent in self.agents
            ],
            'database_documents': self.vector_db.collection.count()
        }
